networks:
    k2r-network:
        name: k2r-network
        driver: bridge

services:
    spring-app:
        container_name: k2r-spring-boot-app
        image: k2r-app
        networks:
            - k2r-network
        ports:
            - "8080:8080"
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            K2R_ACTIVE_PROFILE: "prod"
            K2R_KAFKA_BOOTSTRAP_SERVERS: ${K2R_KAFKA_BOOTSTRAP_SERVERS}
            K2R_RABBIT_HOST: ${K2R_RABBIT_HOST}
            K2R_RABBIT_PORT: ${K2R_RABBIT_PORT}
            K2R_RABBIT_USERNAME: ${K2R_RABBIT_USERNAME}
            K2R_RABBIT_PASSWORD: ${K2R_RABBIT_PASSWORD}
            K2R_DB_URL: ${K2R_DB_URL}
            K2R_DB_NAME: ${K2R_DB_NAME}
            K2R_REDIS_HOST: ${K2R_REDIS_HOST}
            K2R_REDIS_PORT: ${K2R_REDIS_PORT}

    redis:
        container_name: k2r-redis
        image: redis:latest
        networks:
            - k2r-network
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
        driver: local
