networks:
  syntegrico-network:
    name: syntegrico-network
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: syntegrico-redis
    ports:
      - "6379:6379"
    networks:
      - syntegrico-network
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: syntegrico-prometheus
    ports:
      - "9090:9090"
    networks:
      - syntegrico-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: syntegrico-grafana
    ports:
      - "3000:3000"
    networks:
      - syntegrico-network
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana

  spring-boot-app:
    container_name: k2r-spring-boot-app
    image: k2r-app
    networks:
      - syntegrico-network
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      K2R_ACTIVE_PROFILE: "prod"
      K2R_SERVER_PORT: 8080
      K2R_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
      K2R_RABBIT_HOST: localhost
      K2R_RABBIT_PORT: 5672
      K2R_RABBIT_USERNAME: ${K2R_RABBIT_USERNAME}
      K2R_RABBIT_PASSWORD: ${K2R_RABBIT_PASSWORD}
      K2R_DB_URL: ${K2R_DB_URL}
      K2R_DB_NAME: ${K2R_DB_NAME}
      K2R_REDIS_HOST: syntegrico-redis
      K2R_REDIS_PORT: 6379

volumes:
  redis_data:
    driver: local
  grafana_data:
    driver: local