networks:
    syntegrico-network:
        name: syntegrico-network
        driver: bridge

services:

    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: syntegrico-zookeeper
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        ports:
            - "2181:2181"
        networks:
            - syntegrico-network
        volumes:
            - zookeeper_data:/bitnami/zookeeper

    kafka:
        image: bitnami/kafka:latest
        container_name: syntegrico-kafka
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=syntegrico-zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        networks:
            - syntegrico-network
        volumes:
            - kafka_data:/bitnami/kafka

    redis:
        image: redis:latest
        container_name: syntegrico-redis
        ports:
            - "6379:6379"
        networks:
            - syntegrico-network
        volumes:
            - redis_data:/data

    prometheus:
        image: prom/prometheus:latest
        container_name: syntegrico-prometheus
        ports:
            - "9090:9090"
        networks:
            - syntegrico-network
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana:latest
        container_name: syntegrico-grafana
        ports:
            - "3000:3000"
        networks:
            - syntegrico-network
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
        volumes:
            - grafana_data:/var/lib/grafana

    spring-boot-app:
        container_name: k2r-spring-boot-app
        image: k2r-app
        networks:
            - syntegrico-network
        ports:
            - "8080:8080"
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            K2R_ACTIVE_PROFILE: "prod"
            K2R_SERVER_PORT: 8080
            K2R_KAFKA_BOOTSTRAP_SERVERS: syntegrico-kafka:9092
            K2R_RABBIT_HOST: ${K2R_RABBIT_HOST}
            K2R_RABBIT_PORT: ${K2R_RABBIT_PORT}
            K2R_RABBIT_USERNAME: ${K2R_RABBIT_USERNAME}
            K2R_RABBIT_PASSWORD: ${K2R_RABBIT_PASSWORD}
            K2R_DB_URL: ${K2R_DB_URL}
            K2R_DB_NAME: ${K2R_DB_NAME}
            K2R_REDIS_HOST: syntegrico-redis
            K2R_REDIS_PORT: 6379

volumes:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local
    redis_data:
        driver: local
    grafana_data:
        driver: local