networks:
    k2r-network:
        name: k2r-network
        driver: bridge

services:
    spring-app:
        container_name: k2r-spring-boot-app
        image: k2r-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"

    redis:
        image: redis:latest
        container_name: k2r-redis
        ports:
            - "6379:6379"
        networks:
            - k2r-network
        volumes:
            - redis_data:/data

volumes:
    redis_data:
        driver: local