spring:
  application:
    name: SyntegricoKafkaToRabbit
  profiles:
    active: vlad-dev #full-cycle-dev, vlad-dev, prod
  datasource:
    url: jdbc:postgresql://localhost:5432/syntegrico_kafka_rabbit
    username: syntegrico
    password: syntegrico
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: 10.20.4.135:9092 # 10.20.4.135, localhost
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: org.kafka.practice.kafkademo.domain.entities.value
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  rabbitmq:
    host: localhost # 10.20.5.73, localhost
    port: 5672
    username: guest
    password: guest

messaging:
  rabbit:
    routing-key: syntegrico
    redirect-exchange-name: syntegrico-rabbit-message-queue
    response-exchange-name: syntegrico-rabbit-message-response-queue
  kafka:
    group-id: syntegrico-kafka-group
    receive-topic-name: syntegrico-kafka-message-topic
    response-topic-name: syntegrico-kafka-message-topic-response

logging:
  level:
    org.kafka.practice.kafkademo.domain.listeners.RabbitPersonDTOResponseListener: DEBUG
    org.kafka.practice.kafkademo.domain.listeners.KafkaPersonDTORequestListener: DEBUG
    org.kafka.practice.kafkademo.domain.service.RedirectService: DEBUG
    org.kafka.practice.kafkademo.domain.config.KafkaErrorHandler: DEBUG
    org.kafka.practice.kafkademo.domain.dev.NikitaKafkaListener: DEBUG
    org.kafka.practice.kafkademo.domain.dev.VladRabbitListener: DEBUG
    # Transaction logging (TRACE for more info)
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.transaction: DEBUG

random-error-generator:
  error-probability: 20

dev:
  nikita-kafka-producer-delay-ms: 4000