spring:
  application:
    name: KafkaToRabbit
  profiles:
    active: full-cycle-dev #full-cycle-dev, prod
  kafka:
    bootstrap-servers: 25.3.230.68:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: org.kafka.practice.kafkademo.domain.entities.value
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

messaging:
  rabbit:
    routing-key: syntegrico
    redirect-exchange-name: syntegrico-rabbit-message-queue
    response-exchange-name: syntegrico-rabbit-message-response-queue
  kafka:
    group-id: syntegrico-kafka-group
    receive-topic-name: syntegrico-kafka-message-topic
    response-topic-name: syntegrico-kafka-message-topic-response

logging:
  level:
    org.kafka.practice.kafkademo.domain.config.KafkaErrorHandler: TRACE

random-error-generator:
  error-probability: 25