spring:
  application:
    name: SyntegricoKafkaToRabbit
  profiles:
    active: ${K2R_ACTIVE_PROFILE}
  datasource:
    url: ${K2R_DB_URL}
    username: ${K2R_DB_USERNAME}
    password: ${K2R_DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${K2R_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: org.kafka.practice.kafkademo.domain.entities.value
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  rabbitmq:
    host: ${K2R_RABBIT_HOST}
    port: ${K2R_RABBIT_PORT}
    username: ${K2R_RABBIT_USERNAME}
    password: ${K2R_RABBIT_PASSWORD}

messaging:
  rabbit:
    person-dto-routing-key: syntegrico
    person-dto-redirect-exchange-name: syntegrico-rabbit-message-queue
    person-dto-response-exchange-name: syntegrico-rabbit-message-response-queue
  kafka:
    person-dto-group-id: syntegrico-kafka-group
    person-dto-receive-topic-name: syntegrico-kafka-message-topic
    person-dto-response-topic-name: syntegrico-kafka-message-topic-response

logging:
  level:
    # Services log level
    org.kafka.practice.kafkademo.domain.listeners.RabbitPersonDtoResponseListener: ${K2R_SERVICES_LOG_LEVEL}
    org.kafka.practice.kafkademo.domain.listeners.KafkaPersonDtoRequestListener: ${K2R_SERVICES_LOG_LEVEL}
    org.kafka.practice.kafkademo.domain.service.PersonDtoRedirectService: ${K2R_SERVICES_LOG_LEVEL}
    org.kafka.practice.kafkademo.domain.config.KafkaErrorHandler: ${K2R_SERVICES_LOG_LEVEL}
    # Transaction logging (TRACE for more info)
    org.hibernate.type.descriptor.sql.BasicBinder: ${K2R_TRANSACTIONS_LOG_LEVEL}
    org.springframework.transaction: ${K2R_TRANSACTIONS_LOG_LEVEL}
    org.hibernate.transaction: ${K2R_TRANSACTIONS_LOG_LEVEL}
    # Dev profiles logging
    org.kafka.practice.kafkademo.domain.dev.NikitaKafkaListener: ${K2R_DEV_LOG_LEVEL}
    org.kafka.practice.kafkademo.domain.dev.VladRabbitListener: ${K2R_DEV_LOG_LEVEL}
    org.kafka.practice.kafkademo.domain.dev.NikitaScheduler: ${K2R_DEV_LOG_LEVEL}

random-exception-generator:
  exception-probability-percent: 20

dev:
  nikita-kafka-producer-delay-ms: 4000